### ISSUE TITLE
'Robots should not quit' in master

### ISSUE THREAD

**Issue by seanThursby** [FRC3620/FRC3620_2018_CoffeePi#19]
This error code result when I tried to run master. I'm truly not even sure what's wrong, but the robot can't be run. 

********** Robot program starting **********
NT: server: client CONNECTED: 10.36.20.226 port 51751
Log directory is /home/lvuser/logs
1 [org.usfirst.frc3620.robot.RobotMap] INFO - CANDEVICEfinder found [PDP 0]
timestamp for logs is 20190202-113909
Warning at org.usfirst.frc3620.logger.EventLogging.writeWarningToDS(EventLogging.java:92): timestamp for logs is 20190202-113909
Unhandled exception: edu.wpi.first.hal.util.UncleanStatusException: Code: -1029. HAL: Resource already allocated
Error at org.usfirst.frc3620.robot.RobotMap.init(RobotMap.java:139): Unhandled exception: edu.wpi.first.hal.util.UncleanStatusException: Code: -1029. HAL: Resource already allocated
at edu.wpi.first.hal.PWMJNI.initializePWMPort(Native Method)
Robots should not quit, but yours did!
at edu.wpi.first.wpilibj.PWM.<init>(PWM.java:63)
The startCompetition() method (or methods called by it) should have handled the exception above.
at edu.wpi.first.wpilibj.PWMSpeedController.<init>(PWMSpeedController.java:25)
at edu.wpi.first.wpilibj.Spark.<init>(Spark.java:47)
at org.usfirst.frc3620.robot.RobotMap.init(RobotMap.java:139)
at org.usfirst.frc3620.robot.Robot.robotInit(Robot.java:53)
at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:63)
at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:263)
at org.usfirst.frc3620.robot.Main.main(Main.java:20)
Warning at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:274): Robots should not quit, but yours did!
Error at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:276): The startCompetition() method (or methods called by it) should have handled the exception above.
[phoenix] Shutdown cleanly

Line 139 of robotMap is below: 
        lightSubsystemLightPWM = new Spark(5);

**Comment by chaynes2019** [comment]
I don't quite know what to say how to fix it, but here's the API describing the specific "UncleanStatusException":  http://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/hal/util/UncleanStatusException.html

**Comment by Team1557** [comment]
try turning it off and on?
